# to add favicon, upload image to repo and name it favicon.ico

layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: false
    projects:
    # - repo-name

# If you want to include any social media, just uncomment and add username

social_media:
  # behance: your_username
  # devpost: your_username
  # dribbble: your_username
  #  facebook: your_username
  # hackerrank: your_username
    instagram: shreeyakhurana
  # keybase: your_username
   #linkedin: shreeya-khurana-cmu
    linkedin: shreeya-khurana-cmu
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
    twitter: shreeyakhurana
  # unsplash: your_username
  # vk: your_username
  # website: your_username
  # youtube: your_username

portfolio:

# if you want to add mor languages, just add another "title" point underneath language
# be mindful of spacing

  - name: insert name here
    #if no web_url is given, the card won't link to another page and won't hover
    web_url: 
    #if not picture is given, the card will display a gray box with a hastag
    #image must be a url. I recommend uploading pictures to the image repo, pushing repo to Github, then linking pictures from remote repo to local repo. Will be resolving this issue soon
    image_url: 
    description: insert description here
    #give height and width of picture as desired by pixels
    height: 
    width: 
    language:
      - title: HTML/CSS
      - title: JavaScript
      - title: and many more
    date: insert date here

#example
  - name: Github
    web_url: https://github.com/
    image_url: https://github.githubassets.com/images/modules/logos_page/Octocat.png
    description: Access code from around the world!
    height: 64
    width: 64
    language:
      - title: HTML/CSS
      - title: JavaScript
      - title: and many more
    date: 2008 - Present

#you can add as many cards as you like!

experience:
  - name: US Naval Research Laboratoy, Science and Engineering Apprenticeship Program (SEAP) Fellow
    #if no web_url is given, the card won't link to another page and won't hover
    web_url: 
    #if not picture is given, the card will display a gray box with a hastag
    #image must be a url. I recommend uploading pictures to repo, then linking pictures from repo to here. will be resolving this issue soon
    image_url: "images/nrl.jpg"
    description: DESCRIPTION
    #give height and width of picture as desired by pixels
    height: 
    width: 
    date: Jun 2019 - Aug 2019

  - name: Johns Hopkins Applied Physics Laboratory, ASPIRE Intern
    #if no web_url is given, the card won't link to another page and won't hover
    web_url: 
    #if not picture is given, the card will display a gray box with a hastag
    #image must be a url. I recommend uploading pictures to repo, then linking pictures from repo to here. will be resolving this issue soon
    image_url: "images/apl.jpg"
    description: DESCRIPTION
    #give height and width of picture as desired by pixels
    height: 
    width: 
    date: Jun 2018 - Aug 2018

  - name: NASA Goddard Space Flight Center, Student Researcher
    #if no web_url is given, the card won't link to another page and won't hover
    web_url: 
    #if not picture is given, the card will display a gray box with a hastag
    #image must be a url. I recommend uploading pictures to repo, then linking pictures from repo to here. will be resolving this issue soon
    image_url: "images/nasa.jpg"
    description: DESCRIPTION
    #give height and width of picture as desired by pixels
    height: 
    width: 
    date: Jul 2015 - Apr 2018

organizations:
  - name: MATHgirls
    #if no web_url is given, the card won't link to another page and won't hover
    web_url: 
    #if not picture is given, the card will display a gray box with a hastag
    #image must be a url. I recommend uploading pictures to repo, then linking pictures from repo to here. will be resolving this issue soon
    image_url: "images/mathgirls-logo.png"
    description: DESCRIPTION
    #give height and width of picture as desired by pixels
    height: 
    width: 
    date: May 2017 - Present

  - name: ScottyLabs
    #if no web_url is given, the card won't link to another page and won't hover
    web_url: 
    #if not picture is given, the card will display a gray box with a hastag
    #image must be a url. I recommend uploading pictures to repo, then linking pictures from repo to here. will be resolving this issue soon
    image_url: "images/sl-logo.png"
    description: DESCRIPTION
    #give height and width of picture as desired by pixels
    height: 
    width: 
    date: September 2020 - Present
  
  - name: CMIMC
    #if no web_url is given, the card won't link to another page and won't hover
    web_url: 
    #if not picture is given, the card will display a gray box with a hastag
    #image must be a url. I recommend uploading pictures to repo, then linking pictures from repo to here. will be resolving this issue soon
    image_url: "images/cmimc.png"
    description: DESCRIPTION
    #give height and width of picture as desired by pixels
    height: 
    width: 
    date: September 2020 - Present
  
  - name: Women@SCS
    #if no web_url is given, the card won't link to another page and won't hover
    web_url: 
    #if not picture is given, the card will display a gray box with a hastag
    #image must be a url. I recommend uploading pictures to repo, then linking pictures from repo to here. will be resolving this issue soon
    image_url: "images/wscs.png"
    description: DESCRIPTION
    #give height and width of picture as desired by pixels
    height: 
    width: 
    date: September 2020 - Present

  - name: Women@SCS
    #if no web_url is given, the card won't link to another page and won't hover
    web_url: 
    #if not picture is given, the card will display a gray box with a hastag
    #image must be a url. I recommend uploading pictures to repo, then linking pictures from repo to here. will be resolving this issue soon
    image_url: "images/scs4all.png"
    description: DESCRIPTION
    #give height and width of picture as desired by pixels
    height: 
    width: 
    date: September 2020 - Present
events:
-   name: insert name here
    #if no web_url is given, the card won't link to another page and won't hover
    web_url: 
    #if not picture is given, the card will display a gray box with a hastag
    #image must be a url. I recommend uploading pictures to repo, then linking pictures from repo to here. will be resolving this issue soon
    image_url: 
    description: insert description here
    #give height and width of picture as desired by pixels
    height: 
    width: 
    date: 

topics:
  - name: insert name here
    #if no web_url is given, the card won't link to another page and won't hover
    web_url: 
    #if not picture is given, the card will display a gray box with a hastag
    #image must be a url. I recommend uploading pictures to repo, then linking pictures from repo to here. will be resolving this issue soon
    image_url: 
    description: insert description here
    #give height and width of picture as desired by pixels
    height:
    width:
